<?php
$title = 'Deletar Categoria';
$url   = $this->url('categoria', ['action' => 'deletar', 'id' => $id]);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Tem certeza que deseja deletar a categoria?
    "<?= $this->escapeHtml($categoria->nome_categoria); ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $categoria->id_categoria_planejamento ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>