<div class="jumbotron">
    <h1>Bem vindo ao <span class="zf-green">painel</span></h1>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Categorias</h2>
            </div>
            <div class="card-body">
                <p><a class="btn btn-success pull-right" href="/categoria">Cadastrar Categoria &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Produtos</h2>
            </div>
            <div class="card-body">
                <p><a class="btn btn-success pull-right" href="/produto">Cadastrar Prodtuos &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
